URL = 'https://2050d2d3-21e9-4f2c-af2f-afec43b11b1d.serverhub.praktikum-services.ru'
CREATE_ORDER = '/api/v1/orders'
GET_ORDER = '/api/v1/orders/track'
GET_COURIER_LOGIN = '/api/v1/courier/login'
GET_COURIER = '/api/v1/courier'
